/**
 * app.js — DJ Maxim Dokalenko Promo Site
 * Loads all content from JSON files, renders each section.
 * To customise: edit data/content.json, data/events.json, data/music.json
 * and gallery/manifest.json (auto-generated by update-gallery.js)
 */

// ─────────────────────────────────────────────
// UTILITY
// ─────────────────────────────────────────────

async function fetchJSON(path) {
  try {
    const res = await fetch(path);
    if (!res.ok) throw new Error(`HTTP ${res.status} for ${path}`);
    return await res.json();
  } catch (e) {
    console.warn(`[app] Could not load ${path}:`, e.message);
    return null;
  }
}

function el(id) { return document.getElementById(id); }

function formatDate(dateStr) {
  const d = new Date(dateStr + 'T00:00:00');
  return {
    day:  d.toLocaleDateString('en-GB', { day: '2-digit' }),
    mon:  d.toLocaleDateString('en-GB', { month: 'short' }).toUpperCase(),
    year: d.getFullYear(),
    iso:  dateStr
  };
}

function fmtTime(sec) {
  if (isNaN(sec)) return '0:00';
  const m = Math.floor(sec / 60);
  const s = Math.floor(sec % 60).toString().padStart(2, '0');
  return `${m}:${s}`;
}

function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

// ─────────────────────────────────────────────
// TAB ROUTING
// ─────────────────────────────────────────────

function initTabs() {
  const allBtns = document.querySelectorAll('.nav-btn');
  const allTabs = document.querySelectorAll('.tab');

  function activate(tabId) {
    allTabs.forEach(t => t.classList.toggle('active', t.id === `tab-${tabId}`));
    allBtns.forEach(b => b.classList.toggle('active', b.dataset.tab === tabId));
    // Close mobile drawer
    el('mobile-drawer').classList.remove('open');
    el('hamburger').classList.remove('open');
    // Scroll to top
    window.scrollTo({ top: 0, behavior: 'smooth' });
    // Update hash
    history.replaceState(null, '', `#${tabId}`);
  }

  allBtns.forEach(btn => {
    btn.addEventListener('click', () => activate(btn.dataset.tab));
  });

  // CTA button on hero
  document.querySelectorAll('[data-tab]').forEach(btn => {
    if (!btn.classList.contains('nav-btn')) {
      btn.addEventListener('click', () => activate(btn.dataset.tab));
    }
  });

  // Hash routing on load
  const hash = location.hash.replace('#', '');
  if (hash && document.getElementById(`tab-${hash}`)) {
    activate(hash);
  }

  // Hamburger
  el('hamburger').addEventListener('click', () => {
    el('hamburger').classList.toggle('open');
    el('mobile-drawer').classList.toggle('open');
  });
}

// ─────────────────────────────────────────────
// RENDER: HOME
// ─────────────────────────────────────────────

function renderHome(content, events) {
  // Tagline & name
  if (content.tagline) el('hero-tagline').textContent = content.tagline;
  if (content.name)    el('hero-name').innerHTML = content.name.replace(' ', '<br/>');
  if (content.heroDesc || content.description)
    el('hero-desc').textContent = content.heroDesc || content.description;

  // Social links
  const socials = el('hero-socials');
  (content.socials || []).forEach(s => {
    const a = document.createElement('a');
    a.className = 'social-link';
    a.href = s.url;
    a.target = '_blank';
    a.rel = 'noopener noreferrer';
    a.textContent = s.platform.toUpperCase();
    socials.appendChild(a);
  });

  // Ticker — upcoming events or genre tags
  const upcoming = (events || []).filter(e => !e.past).slice(0, 6);
  const tickerItems = upcoming.length
    ? upcoming.map(e => `${e.date} · ${e.title} · ${e.city}`)
    : (content.genres || ['DJ', 'ELECTRONIC', 'MUSIC']);

  const ticker = el('hero-ticker');
  const inner = document.createElement('div');
  inner.className = 'ticker-inner';
  // Duplicate for seamless loop
  const items = [...tickerItems, ...tickerItems];
  items.forEach(t => {
    const span = document.createElement('span');
    span.textContent = t;
    inner.appendChild(span);
  });
  ticker.appendChild(inner);
}

// ─────────────────────────────────────────────
// RENDER: BIO
// ─────────────────────────────────────────────

function renderBio(content) {
  // Bio text — supports plain string or array of paragraphs
  const bioEl = el('bio-text');
  const bioContent = content.bio;
  if (Array.isArray(bioContent)) {
    bioContent.forEach(para => {
      const p = document.createElement('p');
      p.innerHTML = para;
      bioEl.appendChild(p);
    });
  } else if (typeof bioContent === 'string') {
    bioContent.split('\n\n').forEach(para => {
      if (!para.trim()) return;
      const p = document.createElement('p');
      p.innerHTML = para.trim();
      bioEl.appendChild(p);
    });
  }

  // Tags
  const tagsEl = el('bio-tags');
  (content.tags || content.genres || []).forEach(tag => {
    const span = document.createElement('span');
    span.className = 'bio-tag';
    span.textContent = tag.toUpperCase();
    tagsEl.appendChild(span);
  });

  // Bio social links
  const bioSocials = el('bio-socials');
  (content.socials || []).forEach(s => {
    const a = document.createElement('a');
    a.className = 'social-link';
    a.href = s.url;
    a.target = '_blank';
    a.rel = 'noopener noreferrer';
    a.textContent = s.platform.toUpperCase();
    bioSocials.appendChild(a);
  });

  // Photo — update src if specified
  if (content.bioPhoto) {
    el('bio-photo').src = content.bioPhoto;
  }
}

// ─────────────────────────────────────────────
// RENDER: GALLERY
// ─────────────────────────────────────────────

function renderGallery(manifest) {
  const grid = el('gallery-grid');
  if (!manifest || manifest.length === 0) {
    grid.innerHTML = '<p class="events-empty">No gallery images found. Add images to /gallery/ and run update-gallery.js</p>';
    return;
  }

  const images = shuffle(manifest);
  const folder = 'gallery/';

  images.forEach((filename, idx) => {
    const item = document.createElement('div');
    item.className = 'gallery-item';
    item.dataset.index = idx;

    const img = document.createElement('img');
    img.src = folder + filename;
    img.alt = filename.replace(/\.[^.]+$/, '').replace(/[-_]/g, ' ');
    img.loading = 'lazy';

    const overlay = document.createElement('div');
    overlay.className = 'gallery-overlay';
    overlay.innerHTML = '<span>⊕</span>';

    item.appendChild(img);
    item.appendChild(overlay);
    item.addEventListener('click', () => openLightbox(images, idx, folder));
    grid.appendChild(item);
  });
}

// LIGHTBOX
let _lbImages = [];
let _lbFolder = 'gallery/';
let _lbIdx = 0;

function openLightbox(images, idx, folder) {
  _lbImages = images;
  _lbFolder = folder;
  _lbIdx = idx;
  updateLightbox();
  el('lightbox').classList.add('open');
  document.body.style.overflow = 'hidden';
}

function updateLightbox() {
  const src = _lbFolder + _lbImages[_lbIdx];
  el('lightbox-img').src = src;
  el('lightbox-caption').textContent = `${_lbIdx + 1} / ${_lbImages.length} — ${_lbImages[_lbIdx]}`;
}

function closeLightbox() {
  el('lightbox').classList.remove('open');
  document.body.style.overflow = '';
}

function initLightbox() {
  el('lightbox-close').addEventListener('click', closeLightbox);
  el('lightbox-prev').addEventListener('click', () => {
    _lbIdx = (_lbIdx - 1 + _lbImages.length) % _lbImages.length;
    updateLightbox();
  });
  el('lightbox-next').addEventListener('click', () => {
    _lbIdx = (_lbIdx + 1) % _lbImages.length;
    updateLightbox();
  });
  el('lightbox').addEventListener('click', e => {
    if (e.target === el('lightbox')) closeLightbox();
  });
  document.addEventListener('keydown', e => {
    if (!el('lightbox').classList.contains('open')) return;
    if (e.key === 'Escape') closeLightbox();
    if (e.key === 'ArrowLeft') { _lbIdx = (_lbIdx - 1 + _lbImages.length) % _lbImages.length; updateLightbox(); }
    if (e.key === 'ArrowRight') { _lbIdx = (_lbIdx + 1) % _lbImages.length; updateLightbox(); }
  });
}

// ─────────────────────────────────────────────
// RENDER: EVENTS
// ─────────────────────────────────────────────

function renderEvents(events) {
  if (!events || events.length === 0) {
    el('events-upcoming-list').innerHTML = '<p class="events-empty">No upcoming events. Edit data/events.json to add shows.</p>';
    el('events-past-list').innerHTML = '';
    return;
  }

  const today = new Date().toISOString().slice(0, 10);
  const upcoming = events.filter(e => !e.past && e.date >= today).sort((a,b) => a.date.localeCompare(b.date));
  const past     = events.filter(e =>  e.past || e.date < today).sort((a,b) => b.date.localeCompare(a.date));

  function buildCard(evt, isPast) {
    const d = formatDate(evt.date);
    const card = document.createElement('div');
    card.className = `event-card ${isPast ? 'past' : 'upcoming'}`;

    card.innerHTML = `
      <div class="event-date-block">
        <div class="event-day">${d.day}</div>
        <div class="event-mon">${d.mon}</div>
        <div class="event-year">${d.year}</div>
      </div>
      <div class="event-info">
        <div class="event-title">${evt.title}</div>
        ${evt.venue ? `<div class="event-venue">${evt.venue}</div>` : ''}
        ${evt.city  ? `<div class="event-city">${evt.city.toUpperCase()}</div>` : ''}
        ${evt.note  ? `<div class="event-city" style="color:var(--text-2);margin-top:6px">${evt.note}</div>` : ''}
      </div>
      <div class="event-action">
        ${evt.ticketLink && !isPast
          ? `<a href="${evt.ticketLink}" target="_blank" rel="noopener">TICKETS ↗</a>`
          : (evt.ticketLink && isPast ? `<a href="${evt.ticketLink}" target="_blank" rel="noopener">INFO ↗</a>` : '')}
      </div>
    `;
    return card;
  }

  const upEl = el('events-upcoming-list');
  if (upcoming.length) {
    upcoming.forEach(e => upEl.appendChild(buildCard(e, false)));
  } else {
    upEl.innerHTML = '<p class="events-empty">No upcoming events scheduled.</p>';
  }

  const pastEl = el('events-past-list');
  if (past.length) {
    past.forEach(e => pastEl.appendChild(buildCard(e, true)));
  } else {
    pastEl.innerHTML = '<p class="events-empty">No past events recorded.</p>';
  }
}

// ─────────────────────────────────────────────
// RENDER: MUSIC EMBEDS
// ─────────────────────────────────────────────

function renderMusic(music) {
  const embedsEl = el('music-embeds');

  if (music && music.embeds && music.embeds.length) {
    music.embeds.forEach(item => {
      const block = document.createElement('div');
      block.className = 'music-embed-block';
      block.innerHTML = `
        <div class="music-platform-label">${item.platform.toUpperCase()}</div>
        ${item.title ? `<div class="music-embed-title">${item.title}</div>` : ''}
        <div class="embed-wrapper">${item.iframe}</div>
      `;
      embedsEl.appendChild(block);
    });
  } else {
    embedsEl.innerHTML = '<p class="events-empty">No embeds configured. Edit data/music.json to add Mixcloud, SoundCloud, or Bandcamp players.</p>';
  }

  // LOCAL FILES
  const localFiles = music && music.localFiles ? music.localFiles : [];
  const localSection = el('local-player-section');

  if (localFiles.length === 0) {
    localSection.querySelector('h3').insertAdjacentHTML('afterend', '<p class="events-empty">No local files configured. Edit data/music.json → localFiles.</p>');
    return;
  }

  initAudioPlayer(localFiles);
}

// ─────────────────────────────────────────────
// AUDIO PLAYER
// ─────────────────────────────────────────────

function initAudioPlayer(tracks) {
  const audioEl = el('audio-el');
  const playerBar = el('audio-player-bar');
  const trackList = document.createElement('div');
  trackList.className = 'track-list';
  el('local-tracks').appendChild(trackList);

  let currentIdx = -1;
  let isPlaying = false;

  // Build track list
  tracks.forEach((track, i) => {
    const item = document.createElement('div');
    item.className = 'track-item';
    item.dataset.idx = i;
    item.innerHTML = `
      <span class="track-num">${String(i + 1).padStart(2, '0')}</span>
      <span class="track-name">${track.title}</span>
      <span class="track-play-icon">▶</span>
    `;
    item.addEventListener('click', () => playTrack(i));
    trackList.appendChild(item);
  });

  function playTrack(idx) {
    currentIdx = idx;
    const track = tracks[idx];
    audioEl.src = track.file;
    audioEl.play();
    isPlaying = true;
    el('player-play').textContent = '⏸';
    el('player-track-name').textContent = track.title;
    playerBar.style.display = 'grid';

    document.querySelectorAll('.track-item').forEach((t, i) => {
      t.classList.toggle('playing', i === idx);
    });
  }

  el('player-play').addEventListener('click', () => {
    if (currentIdx === -1) { playTrack(0); return; }
    if (isPlaying) { audioEl.pause(); el('player-play').textContent = '▶'; isPlaying = false; }
    else           { audioEl.play();  el('player-play').textContent = '⏸'; isPlaying = true;  }
  });

  el('player-prev').addEventListener('click', () => {
    if (currentIdx > 0) playTrack(currentIdx - 1);
  });

  el('player-next').addEventListener('click', () => {
    if (currentIdx < tracks.length - 1) playTrack(currentIdx + 1);
  });

  audioEl.addEventListener('ended', () => {
    if (currentIdx < tracks.length - 1) playTrack(currentIdx + 1);
    else { isPlaying = false; el('player-play').textContent = '▶'; }
  });

  audioEl.addEventListener('timeupdate', () => {
    if (!audioEl.duration) return;
    el('player-seek').value = (audioEl.currentTime / audioEl.duration) * 100;
    el('player-time-cur').textContent = fmtTime(audioEl.currentTime);
    el('player-time-dur').textContent = fmtTime(audioEl.duration);
  });

  el('player-seek').addEventListener('input', e => {
    if (!audioEl.duration) return;
    audioEl.currentTime = (e.target.value / 100) * audioEl.duration;
  });

  el('player-vol').addEventListener('input', e => {
    audioEl.volume = e.target.value / 100;
  });
  audioEl.volume = 0.8;
}

// ─────────────────────────────────────────────
// RENDER: PROMO
// ─────────────────────────────────────────────

function renderPromo(content) {
  const promo = content.promo;
  const stage = el('promo-stage');

  if (!promo) {
    stage.innerHTML = '<p class="events-empty">No promo configured. Edit data/content.json → promo block.</p>';
    return;
  }

  const typeLabel = (promo.type || 'promo').toUpperCase();

  let imageHtml = '';
  if (promo.image) {
    imageHtml = `<img class="promo-image" src="${promo.image}" alt="${promo.title || ''}" />`;
  }

  let ctaHtml = '';
  if (promo.link) {
    ctaHtml = `<a class="promo-cta" href="${promo.link}" target="_blank" rel="noopener">${promo.cta || 'FIND OUT MORE ↗'}</a>`;
  }

  let noteHtml = '';
  if (promo.note) {
    noteHtml = `<div class="promo-note-text">${promo.note}</div>`;
  }

  stage.innerHTML = `
    <div class="promo-card">
      ${imageHtml}
      <div class="promo-body">
        <span class="promo-type-badge">${typeLabel}</span>
        ${promo.title    ? `<div class="promo-title">${promo.title}</div>` : ''}
        ${promo.subtitle ? `<div class="promo-subtitle">${promo.subtitle}</div>` : ''}
        ${promo.date     ? `<div class="promo-date">⬥ ${promo.date}</div>` : ''}
        ${ctaHtml}
      </div>
      ${noteHtml}
    </div>
  `;
}

// ─────────────────────────────────────────────
// RENDER: FOOTER
// ─────────────────────────────────────────────

function renderFooter(content) {
  if (content.name) el('footer-name').textContent = content.name.toUpperCase();

  const footerSocials = el('footer-socials');
  (content.socials || []).forEach(s => {
    const a = document.createElement('a');
    a.className = 'social-link';
    a.href = s.url;
    a.target = '_blank';
    a.rel = 'noopener noreferrer';
    a.textContent = s.platform.toUpperCase();
    footerSocials.appendChild(a);
  });

  el('footer-copy').textContent = `© ${new Date().getFullYear()} ${content.name || 'Maxim Dokalenko'}`;
}

// ─────────────────────────────────────────────
// BOOT
// ─────────────────────────────────────────────

async function init() {
  initTabs();
  initLightbox();

  // Load all data in parallel
  const [content, events, music, manifest] = await Promise.all([
    fetchJSON('data/content.json'),
    fetchJSON('data/events.json'),
    fetchJSON('data/music.json'),
    fetchJSON('gallery/manifest.json')
  ]);

  const safeContent = content || {};
  const safeEvents  = events  || [];
  const safeMusic   = music   || {};

  renderHome(safeContent, safeEvents);
  renderBio(safeContent);
  renderGallery(manifest || []);
  renderEvents(safeEvents);
  renderMusic(safeMusic);
  renderPromo(safeContent);
  renderFooter(safeContent);
}

document.addEventListener('DOMContentLoaded', init);
